# action.yml
name: 'Mutex'
description: 'A simple locking/unlocking mechanism to provide mutual exclusion in Github Actions'
inputs:
  repo-token:
    description: 'The token for accessing the repo.'
    required: true
  branch:
    description: 'The branch to use for the mutex'
    required: false
    default: 'gh-mutex'
  internal_checkout-location:
    description: '[Internal] The location to store the mutex repo'
    required: false
    default: '/run/gh-action-mutex/repo'
  internal_repository:
    description: '[Internal] The github repository'
    required: false
    default: ${{ github.repository }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ARG_BRANCH: ${{ inputs.branch }}
    ARG_CHECKOUT_LOCATION: ${{ inputs.internal_checkout-location }}
    ARG_REPOSITORY: ${{ inputs.internal_repository }}
    ARG_REPO_TOKEN: ${{ inputs.repo-token }}
  entrypoint: '/scripts/lock.sh'
  post-entrypoint: '/scripts/unlock.sh'

