on: [push]

jobs:
  simple_test:
    runs-on: ubuntu-latest
    name: Simple mutex test
    steps:
      - uses: actions/checkout@v3
      - name: Set up mutex
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "I am protected!"
          sleep 5

  two_clients_test_client_1:
    runs-on: ubuntu-latest
    name: Two clients test (client 1)
    needs: [simple_test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up mutex
        uses: ./
        with:
          branch: gh-mutex-two-clients-test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "I am protected!"
          sleep 20

  two_clients_test_client_2:
    runs-on: ubuntu-latest
    name: Two clients test (client 2)
    needs: [simple_test]
    steps:
      - uses: actions/checkout@v3
      - name: Set up mutex
        uses: ./
        with:
          branch: gh-mutex-two-clients-test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "I am protected!"
          sleep 20

