on: [push]

jobs:
  simple_test:
    runs-on: ubuntu-latest
    name: Simple mutex test
    steps:
      - uses: actions/checkout@v3
      - name: Set up mutex
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo "I am protected!"
          sleep 5

